inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable

  Exclude:
    - bin/*
    - db/migrate/**/*
    - node_modules/**/*

  Include:
    - "**/*.rake"
    - "**/Gemfile"
    - "**/Rakefile"
